### ISSUE TITLE
How can I restore my training?

### ISSUE THREAD

**Issue by Jaycebox** [seasonSH/WarpGAN#1]
I use google colab to train WarpGAN model.
Because the training time is too long, I have to stop it and save my log files.

Now, I want to continue my training.
Can I restore my training?

**Comment by ronny3050** [comment]
Yes, you can restore training by modifying the config code:
```
# Restore model
restore_model = "TRAINING_MODEL_DIRECTORY"

# Keywords to filter restore variables, set None for all
restore_scopes =  None
```
