### ISSUE TITLE
About the Pre-Trained Discriminator Model

### ISSUE THREAD

**Issue by firattamur** [seasonSH/WarpGAN#8]
Hello,

Why do we need to download pre-trained discriminator model for [training](https://github.com/seasonSH/WarpGAN#training)? Could we train discriminator model from scratch without the pre-trained model? 

Thanks

**Comment by ronny3050** [comment]
Hi Firat, the discriminator is a pre-trained face recognition model. Generally caricature datasets have only a few subjects and therefore, the discriminator cannot learn distinguishing and robust face features. Therefore, we recommend using the pre-trained discriminator.

**Comment by 0xfirattamur** [comment]
Hello Ronny,

Thank you for your quick reply. We would like to implement PyTorch version of WarpGAN to share this interesting project with PyTorch community. How could we use pre-trained model in PyTorch? Is there any pre-trained discriminator model for PyTorch?

Best Regards,

**Comment by ronny3050** [comment]
You can use any pre-trained face recognition system (just remove the fully-connected/dense layer at the end). For example, https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch

**Comment by 0xfirattamur** [comment]
Thanks a lot!
